spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/james_store
spring.datasource.username=Anesu
spring.datasource.password=Taps1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect